export enum Dialog {
  CONFIRM_ACTION = 'CONFIRM_ACTION',
  CREATE_CHANNEL = 'CREATE_CHANNEL',
  TEXT_INPUT = 'TEXT_INPUT',
  ASSIGN_ROLE = 'ASSIGN_ROLE',
  CREATE_INVITE = 'CREATE_INVITE',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  PLUGIN_LOGS = 'PLUGIN_LOGS',
  PLUGIN_COMMANDS = 'PLUGIN_COMMANDS',
  PLUGIN_SETTINGS = 'PLUGIN_SETTINGS',
  CLAIM_ADMIN = 'CLAIM_ADMIN',
  CREATE_SERVER = 'CREATE_SERVER'
}
